### ISSUE TITLE
Missing last entry's unit in pm25 data scraper output

### ISSUE THREAD

**Issue by mjstealey** [mjstealey/datatranslator#7]
@lstillwe - Looking at the pm25.csv sample there are a couple oddities.

1. The last row is missing the **unit** information 
2. The **unit** text is fugly for loading into PostgreSQL

<img width="1047" alt="screen shot 2017-03-20 at 3 56 13 pm" src="https://cloud.githubusercontent.com/assets/5332509/24119003/2740e540-0d86-11e7-9d8a-36cf5cdbe87a.png">

Wondering if we can validate the final unit information being added, and while at it replace the units with standard text, i.e. ugm3 instead of the superscripted bits.

I've done this manually on the sample found in [pm25_raw](https://github.com/mjstealey/datatranslator/tree/master/sample-data/pm25_raw)

**Comment by lstillwe** [comment]
Huh - thats weird. I’ll check it out.

Lisa
On Mar 20, 2017, at 4:03 PM, Michael J. Stealey <notifications@github.com<mailto:notifications@github.com>> wrote:


@lstillwe<https://github.com/lstillwe> - Looking at the pm25.csv sample there are a couple oddities.

  1.  The last row is missing the unit information
  2.  The unit text is fugly for loading into PostgreSQL

[screen shot 2017-03-20 at 3 56 13 pm]<https://cloud.githubusercontent.com/assets/5332509/24119003/2740e540-0d86-11e7-9d8a-36cf5cdbe87a.png>

Wondering if we can validate the final unit information being added, and while at it replace the units with standard text, i.e. ugm3 instead of the superscripted bits.

I've done this manually on the sample found in pm25_raw<https://github.com/mjstealey/datatranslator/tree/master/sample-data/pm25_raw>

**Comment by lstillwe** [comment]
Michael,

The unit characters (mu, etc) look okay in the raw text file. I wonder if this is an issue in Excel? I wonder if this necessarily translates to a problem importing into the DB?

It looks like now there is an issue retrieving the data for Wilmington - getting a http 400 error message. So this explains why the data didn’t finish writing.
I’ll add a flush of the writer stream just before exiting with the 400 error, but this does not fix the problem. I wish I could find out why certain cities are causing this error. Maybe I should ask James about it.

Lisa

On Mar 20, 2017, at 4:31 PM, Lisa Stillwell <lisa@renci.org<mailto:lisa@renci.org>> wrote:

Huh - thats weird. I’ll check it out.

Lisa
On Mar 20, 2017, at 4:03 PM, Michael J. Stealey <notifications@github.com<mailto:notifications@github.com>> wrote:


@lstillwe<https://github.com/lstillwe> - Looking at the pm25.csv sample there are a couple oddities.

  1.  The last row is missing the unit information
  2.  The unit text is fugly for loading into PostgreSQL

[screen shot 2017-03-20 at 3 56 13 pm]<https://cloud.githubusercontent.com/assets/5332509/24119003/2740e540-0d86-11e7-9d8a-36cf5cdbe87a.png>

Wondering if we can validate the final unit information being added, and while at it replace the units with standard text, i.e. ugm3 instead of the superscripted bits.

I've done this manually on the sample found in pm25_raw<https://github.com/mjstealey/datatranslator/tree/master/sample-data/pm25_raw>

**Comment by mjstealey** [comment]
> The unit characters (mu, etc) look okay in the raw text file. I wonder if this is an issue in Excel?

@lstillwe - That could very well be the case. I did open the file in excel and it may have saved unwanted bits into the source file after adding the last empty unit to the file. Will have to redo without excel in the loop and see if that makes a difference.

**Comment by lstillwe** [comment]
Looking at this some more,I think the http 400 errors actually are caused by spaces in some of the city and location values. I will encode with "%20" and test.

**Comment by lstillwe** [comment]
@mjstealey - I believe this is fixed now - can I close?

**Comment by mjstealey** [comment]
closing
